variables:
  IMAGE: ubuntu:bionic-20220315
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/magisk-emoji/${CI_COMMIT_TAG}"

stages:
  - build
  - upload
  - release

build-noto:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building Noto"
    - source env_noto.sh
    - ./buildNoto.sh --build
  artifacts:
    paths:
      - "out/*.zip"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - out/

build-ios:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building iOS"
    - source env_ios.sh 
    - ./buildIOS.sh --build
  artifacts:
    paths:
      - "out/*.zip"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - out/

upload:
  image: $IMAGE
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt update && apt install -y curl
    - ls out/
    - ./buildNoto.sh --upload
    - ./buildIOS.sh --upload



release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ls */*
    - NOTO=$(ls -r out | head -1 | tail -1)
    - IOS=$(ls -r out | head -2 | tail -1)
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${NOTO}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${NOTO}\"}" \
        --assets-link "{\"name\":\"${IOS}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${IOS}\"}"
