variables:
  IMAGE: ubuntu:bionic-20220315

stages:
  - build
#  - test
#  - deploy
  - release

build-noto:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building Noto"
    - ./buildNoto.sh
  artifacts:
    paths:
      - "out/*.zip"

build-ios:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building iOS"
    - ./buildIOS.sh
  artifacts:
    paths:
      - "out/*.zip"

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'                                       # elsewhere in the pipeline.
    ref: '$CI_COMMIT_TAG'
