variables:
  IMAGE: ubuntu:bionic-20220315

stages:
  - build
#  - test
#  - deploy

build-noto:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building Noto"
    - ./buildNoto.sh

build-ios:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building iOS"
    - ./buildIOS.sh

