variables:
  IMAGE: ubuntu:bionic-20220315
  NOTO_NAME: Magisk-Emoji-Font-noto-v2.034-2.zip
  IOS_NAME: Magisk-Emoji-Font-ios-v15.4-2.zip
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/me-release/${PACKAGE_VERSION}"

stages:
  - build
  - upload
  - release

build-noto:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building Noto"
    - ./buildNoto.sh
  artifacts:
    paths:
      - "out/*.zip"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - out/

build-ios:
  image: $IMAGE
  stage: build
  script:
    - apt update && apt install -y zip
    - echo "Building iOS"
    - ./buildIOS.sh
  artifacts:
    paths:
      - "out/*.zip"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - out/

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/${NOTO_NAME} "${PACKAGE_REGISTRY_URL}/${NOTO_NAME}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/${IOS_NAME} "${PACKAGE_REGISTRY_URL}/${IOS_NAME}"


upload:
  image: $IMAGE
  stage: upload
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - echo "Uploading artifacts"
  artifacts:
    expire_in: never
    paths:
      - "out/*.zip"


release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${NOTO_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${NOTO_NAME}\"}" \
        --assets-link "{\"name\":\"${IOS_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${IOS_NAME}\"}"
